Regenerated baseline with `vimeo/psalm:^5`, refined test types
Note: we didn't touch detected redundant casts nor `src/`, since all
reported issues would require some potential BC breaks or architectural
changes, in order to be fixed.

These were the newly introduced issues:

```
ERROR: MixedInferredReturnType - src/CodeGenerator/AbstractInjector.php:77:16 - Could not verify return type 'T' for Laminas\Di\CodeGenerator\AbstractInjector::create (see https://psalm.dev/047)
     * @return T

ERROR: MixedReturnStatement - src/CodeGenerator/AbstractInjector.php:82:20 - Could not infer a return type (see https://psalm.dev/138)
            return $this->getFactory($name)->create($this->container, $options);

  The type of $this->getFactory($name)->create($this->container, $options) is sourced from here - src/CodeGenerator/FactoryInterface.php:18:16
     * @return T

ERROR: InvalidReturnStatement - src/CodeGenerator/AbstractInjector.php:85:16 - The inferred type 'object' does not match the declared return type 'T:fn-laminas\di\codegenerator\abstractinjector::create as object' for Laminas\Di\CodeGenerator\AbstractInjector::create (see https://psalm.dev/128)
        return $this->injector->create($name, $options);

ERROR: MixedArrayAccess - src/Config.php:196:23 - Cannot access array value on mixed variable $this->types[$context]['preferences'] (see https://psalm.dev/051)
        $preference = $this->types[$context]['preferences'][$type];

ERROR: InvalidReturnType - src/Container/AutowireFactory.php:57:16 - The declared return type 'T:fn-laminas\di\container\autowirefactory::create as object' for Laminas\Di\Container\AutowireFactory::create is incorrect, got 'object' (see https://psalm.dev/011)
     * @return T

ERROR: InvalidReturnStatement - src/Container/AutowireFactory.php:61:16 - The inferred type 'object' does not match the declared return type 'T:fn-laminas\di\container\autowirefactory::create as object' for Laminas\Di\Container\AutowireFactory::create (see https://psalm.dev/128)
        return $this->getInjector($container)->create($requestedName, $options ?: []);

ERROR: InvalidReturnType - src/Container/AutowireFactory.php:70:16 - The declared return type 'T:fn-laminas\di\container\autowirefactory::__invoke as object' for Laminas\Di\Container\AutowireFactory::__invoke is incorrect, got 'object' (see https://psalm.dev/011)
     * @return T

ERROR: InvalidReturnStatement - src/Container/AutowireFactory.php:75:16 - The inferred type 'object' does not match the declared return type 'T:fn-laminas\di\container\autowirefactory::__invoke as object' for Laminas\Di\Container\AutowireFactory::__invoke (see https://psalm.dev/128)
        return $this->create($container, (string) $requestedName, $options);

ERROR: InvalidReturnType - src/Injector.php:116:16 - The declared return type 'T:fn-laminas\di\injector::create as object' for Laminas\Di\Injector::create is incorrect, got 'object' (see https://psalm.dev/011)
     * @return T

ERROR: InvalidReturnStatement - src/Injector.php:138:16 - The inferred type 'object' does not match the declared return type 'T:fn-laminas\di\injector::create as object' for Laminas\Di\Injector::create (see https://psalm.dev/128)
        return $instance;

ERROR: RedundantCast - src/Injector.php:231:21 - Redundant cast to int (see https://psalm.dev/262)
                    (int) $containerException->getCode(),

ERROR: MissingTemplateParam - test/Resolver/DependencyResolverTest.php:374:86 - _home_ocramius_Documents_laminas_laminas_di_test_Resolver_DependencyResolverTest_php_374_13667 has missing template params when extending IteratorAggregate, expecting 2 (see https://psalm.dev/182)
            'iterableIteratorAggregate' => ['iterable',         new class implements IteratorAggregate

ERROR: InvalidReturnType - test/TestAsset/GeneratedInjector.php:33:16 - The declared return type 'T:fn-laminastest\di\testasset\generatedinjector::create as object' for LaminasTest\Di\TestAsset\GeneratedInjector::create is incorrect, got 'object' (see https://psalm.dev/011)
     * @return T

ERROR: InvalidReturnStatement - test/TestAsset/GeneratedInjector.php:37:16 - The inferred type 'object' does not match the declared return type 'T:fn-laminastest\di\testasset\generatedinjector::create as object' for LaminasTest\Di\TestAsset\GeneratedInjector::create (see https://psalm.dev/128)
        return $this->injector->create($name, $options);
```

Note how type inference on `string|class-string<T> -> T` regressed,
because psalm correctly operates on union types now: this still
works from a caller PoV, so it's only an internal problem, for now.